<a href="https://colab.research.google.com/github/omkar24102000/Anshul706/blob/main/Spam_Ham_BOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import pandas as pd

In [64]:

messages = pd.read_csv(
    '/spam.csv',
    encoding='latin1'
)

In [65]:
messages = messages.rename(
    columns={
        'v1': 'label',
        'v2': 'message'
    }
)

In [66]:
messages = messages[['label', 'message']]

In [67]:
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [68]:
## BOW, TFIDF, Machine learning

In [69]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [70]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [71]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [72]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2),binary=True)

In [73]:
#INDEPENDENT FEATURE
X = cv.fit_transform(corpus).toarray()

In [74]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [75]:
cv.vocabulary_

{'go': np.int64(823),
 'point': np.int64(1633),
 'crazi': np.int64(449),
 'avail': np.int64(122),
 'bugi': np.int64(226),
 'great': np.int64(870),
 'world': np.int64(2422),
 'la': np.int64(1103),
 'cine': np.int64(351),
 'got': np.int64(861),
 'wat': np.int64(2321),
 'ok': np.int64(1476),
 'lar': np.int64(1116),
 'joke': np.int64(1060),
 'wif': np.int64(2375),
 'oni': np.int64(1498),
 'ok lar': np.int64(1479),
 'free': np.int64(739),
 'entri': np.int64(616),
 'wkli': np.int64(2405),
 'comp': np.int64(402),
 'win': np.int64(2380),
 'cup': np.int64(463),
 'final': np.int64(696),
 'st': np.int64(1966),
 'may': np.int64(1268),
 'text': np.int64(2095),
 'receiv': np.int64(1720),
 'question': np.int64(1689),
 'std': np.int64(1982),
 'txt': np.int64(2200),
 'rate': np.int64(1701),
 'appli': np.int64(87),
 'free entri': np.int64(746),
 'entri wkli': np.int64(618),
 'wkli comp': np.int64(2406),
 'std txt': np.int64(1983),
 'txt rate': np.int64(2206),
 'rate appli': np.int64(1702),
 'dun': np.int64(574),
 'say': np.int64(1807),
 'earli': np.int64(580),
 'alreadi': np.int64(60),
 'nah': np.int64(1373),
 'think': np.int64(2114),
 'goe': np.int64(841),
 'usf': np.int64(2266),
 'live': np.int64(1183),
 'around': np.int64(98),
 'though': np.int64(2122),
 'freemsg': np.int64(759),
 'hey': np.int64(928),
 'darl': np.int64(486),
 'week': np.int64(2341),
 'word': np.int64(2415),
 'back': np.int64(139),
 'like': np.int64(1169),
 'fun': np.int64(783),
 'still': np.int64(1985),
 'tb': np.int64(2071),
 'xxx': np.int64(2462),
 'send': np.int64(1836),
 'even': np.int64(628),
 'brother': np.int64(217),
 'speak': np.int64(1943),
 'treat': np.int64(2179),
 'per': np.int64(1559),
 'request': np.int64(1752),
 'oru': np.int64(1523),
 'set': np.int64(1852),
 'callertun': np.int64(273),
 'caller': np.int64(270),
 'press': np.int64(1662),
 'copi': np.int64(432),
 'friend': np.int64(765),
 'per request': np.int64(1565),
 'set callertun': np.int64(1853),
 'callertun caller': np.int64(274),
 'caller press': np.int64(271),
 'press copi': np.int64(1663),
 'copi friend': np.int64(433),
 'friend callertun': np.int64(766),
 'winner': np.int64(2389),
 'valu': np.int64(2273),
 'network': np.int64(1398),
 'custom': np.int64(468),
 'select': np.int64(1830),
 'prize': np.int64(1671),
 'reward': np.int64(1763),
 'claim': np.int64(354),
 'call': np.int64(242),
 'code': np.int64(376),
 'valid': np.int64(2271),
 'hour': np.int64(969),
 'claim call': np.int64(355),
 'call claim': np.int64(246),
 'claim code': np.int64(356),
 'mobil': np.int64(1318),
 'month': np.int64(1338),
 'entitl': np.int64(614),
 'updat': np.int64(2231),
 'latest': np.int64(1128),
 'colour': np.int64(388),
 'camera': np.int64(281),
 'co': np.int64(373),
 'entitl updat': np.int64(615),
 'updat latest': np.int64(2233),
 'latest colour': np.int64(1130),
 'free call': np.int64(742),
 'call mobil': np.int64(256),
 'mobil updat': np.int64(1327),
 'updat co': np.int64(2232),
 'co free': np.int64(374),
 'gonna': np.int64(846),
 'home': np.int64(954),
 'soon': np.int64(1927),
 'want': np.int64(2310),
 'talk': np.int64(2066),
 'stuff': np.int64(2014),
 'anymor': np.int64(76),
 'tonight': np.int64(2162),
 'cri': np.int64(453),
 'enough': np.int64(611),
 'today': np.int64(2146),
 'want talk': np.int64(2317),
 'chanc': np.int64(323),
 'cash': np.int64(304),
 'pound': np.int64(1648),
 'cost': np.int64(435),
 'day': np.int64(493),
 'repli': np.int64(1744),
 'hl': np.int64(940),
 'info': np.int64(1012),
 'chanc win': np.int64(325),
 'win cash': np.int64(2381),
 'repli hl': np.int64(1746),
 'hl info': np.int64(941),
 'urgent': np.int64(2255),
 'www': np.int64(2444),
 'net': np.int64(1395),
 'pobox': np.int64(1628),
 'ldnw': np.int64(1142),
 'week free': np.int64(2343),
 'txt word': np.int64(2208),
 'search': np.int64(1816),
 'right': np.int64(1765),
 'thank': np.int64(2104),
 'promis': np.int64(1681),
 'wont': np.int64(2414),
 'take': np.int64(2059),
 'help': np.int64(926),
 'wonder': np.int64(2412),
 'bless': np.int64(188),
 'time': np.int64(2133),
 'date': np.int64(491),
 'sunday': np.int64(2030),
 'use': np.int64(2264),
 'credit': np.int64(451),
 'click': np.int64(368),
 'wap': np.int64(2318),
 'link': np.int64(1178),
 'next': np.int64(1412),
 'messag': np.int64(1284),
 'http': np.int64(978),
 'com': np.int64(391),
 'oh': np.int64(1472),
 'watch': np.int64(2325),
 'eh': np.int64(593),
 'rememb': np.int64(1737),
 'spell': np.int64(1953),
 'name': np.int64(1375),
 'ye': np.int64(2471),
 'naughti': np.int64(1383),
 'make': np.int64(1242),
 'wet': np.int64(2362),
 'fine': np.int64(703),
 'way': np.int64(2328),
 'feel': np.int64(680),
 'england': np.int64(607),
 'dont': np.int64(554),
 'miss': np.int64(1306),
 'team': np.int64(2077),
 'news': np.int64(1411),
 'ur': np.int64(2234),
 'nation': np.int64(1379),
 'eg': np.int64(591),
 'tri': np.int64(2180),
 'wq': np.int64(2435),
 'dont miss': np.int64(556),
 'serious': np.int64(1848),
 'ha': np.int64(897),
 'ha ha': np.int64(898),
 'pay': np.int64(1551),
 'first': np.int64(708),
 'da': np.int64(475),
 'stock': np.int64(1989),
 'comin': np.int64(400),
 'aft': np.int64(33),
 'finish': np.int64(706),
 'lunch': np.int64(1232),
 'str': np.int64(2007),
 'lor': np.int64(1205),
 'ard': np.int64(92),
 'smth': np.int64(1908),
 'alright': np.int64(61),
 'meet': np.int64(1275),
 'forc': np.int64(727),
 'eat': np.int64(586),
 'realli': np.int64(1716),
 'hungri': np.int64(983),
 'tho': np.int64(2121),
 'suck': np.int64(2022),
 'mark': np.int64(1254),
 'get': np.int64(802),
 'worri': np.int64(2424),
 'know': np.int64(1095),
 'sick': np.int64(1874),
 'turn': np.int64(2196),
 'pizza': np.int64(1593),
 'lol': np.int64(1195),
 'alway': np.int64(64),
 'catch': np.int64(313),
 'bu': np.int64(222),
 'fri': np.int64(763),
 'egg': np.int64(592),
 'tea': np.int64(2075),
 'mom': np.int64(1333),
 'left': np.int64(1150),
 'dinner': np.int64(537),
 'love': np.int64(1211),
 'amp': np.int64(67),
 'pack': np.int64(1534),
 'car': np.int64(294),
 'let': np.int64(1157),
 'room': np.int64(1775),
 'let know': np.int64(1158),
 'work': np.int64(2418),
 'feel like': np.int64(684),
 'wait': np.int64(2298),
 'clear': np.int64(367),
 'sure': np.int64(2042),
 'us': np.int64(2263),
 'yeah': np.int64(2476),
 'child': np.int64(342),
 'till': np.int64(2132),
 'cheer': np.int64(338),
 'yeah got': np.int64(2477),
 'tell': np.int64(2085),
 'anyth': np.int64(78),
 'tell anyth': np.int64(2086),
 'quick': np.int64(1690),
 'subscript': np.int64(2020),
 'rington': np.int64(1768),
 'uk': np.int64(2215),
 'charg': np.int64(329),
 'pleas': np.int64(1611),
 'confirm': np.int64(412),
 'mobil charg': np.int64(1320),
 'repli ye': np.int64(1748),
 'yup': np.int64(2496),
 'look': np.int64(1201),
 'msg': np.int64(1357),
 'learn': np.int64(1144),
 'nd': np.int64(1384),
 'lesson': np.int64(1156),
 'yup ok': np.int64(2497),
 'ok go': np.int64(1478),
 'go home': np.int64(829),
 'oop': np.int64(1502),
 'roommat': np.int64(1776),
 'done': np.int64(553),
 'see': np.int64(1824),
 'letter': np.int64(1159),
 'decid': np.int64(510),
 'anyth lor': np.int64(79),
 'hello': np.int64(925),
 'saturday': np.int64(1801),
 'tomo': np.int64(2154),
 'invit': np.int64(1024),
 'pl': np.int64(1594),
 'ahead': np.int64(42),
 'weekend': np.int64(2348),
 'abiola': np.int64(2),
 'great weekend': np.int64(872),
 'forget': np.int64(729),
 'need': np.int64(1388),
 'crave': np.int64(448),
 'sweet': np.int64(2051),
 'need crave': np.int64(1390),
 'burn': np.int64(229),
 'sm': np.int64(1902),
 'nokia': np.int64(1426),
 'camcord': np.int64(276),
 'deliveri': np.int64(520),
 'tomorrow': np.int64(2155),
 'call repli': np.int64(261),
 'free nokia': np.int64(752),
 'nokia mobil': np.int64(1431),
 'mobil free': np.int64(1324),
 'free camcord': np.int64(743),
 'pleas call': np.int64(1612),
 'deliveri tomorrow': np.int64(521),
 'hope': np.int64(958),
 'man': np.int64(1246),
 'well': np.int64(2355),
 'lt': np.int64(1223),
 'gt': np.int64(877),
 'inch': np.int64(1005),
 'lt gt': np.int64(1225),
 'miss call': np.int64(1309),
 'nigeria': np.int64(1417),
 'tyler': np.int64(2212),
 'could': np.int64(440),
 'mayb': np.int64(1269),
 'ask': np.int64(106),
 'bit': np.int64(184),
 'hospit': np.int64(964),
 'kept': np.int64(1078),
 'weak': np.int64(2334),
 'want go': np.int64(2313),
 'saw': np.int64(1806),
 'class': np.int64(364),
 'first time': np.int64(709),
 'usual': np.int64(2267),
 'run': np.int64(1785),
 'half': np.int64(903),
 'almost': np.int64(58),
 'whole': np.int64(2370),
 'second': np.int64(1819),
 'like lt': np.int64(1172),
 'fyi': np.int64(786),
 'ride': np.int64(1764),
 'morn': np.int64(1343),
 'place': np.int64(1603),
 'wow': np.int64(2432),
 'never': np.int64(1402),
 'realiz': np.int64(1715),
 'thought': np.int64(2123),
 'sinc': np.int64(1882),
 'best': np.int64(175),
 'seem': np.int64(1828),
 'happi': np.int64(910),
 'sorri': np.int64(1929),
 'give': np.int64(817),
 'offer': np.int64(1464),
 'ac': np.int64(5),
 'new': np.int64(1403),
 'red': np.int64(1725),
 'play': np.int64(1605),
 'ice': np.int64(989),
 'correct': np.int64(434),
 'end': np.int64(600),
 'sm ac': np.int64(1903),
 'yesterday': np.int64(2486),
 'find': np.int64(698),
 'congrat': np.int64(413),
 'year': np.int64(2480),
 'special': np.int64(1946),
 'cinema': np.int64(352),
 'pass': np.int64(1546),
 'etc': np.int64(624),
 'bx': np.int64(233),
 'ip': np.int64(1028),
 'pm': np.int64(1622),
 'etc free': np.int64(625),
 'bx ip': np.int64(234),
 'ip pm': np.int64(1029),
 'later': np.int64(1125),
 'sorri call': np.int64(1930),
 'call later': np.int64(254),
 'later meet': np.int64(1126),
 'reach': np.int64(1708),
 'pick': np.int64(1583),
 'move': np.int64(1349),
 'pain': np.int64(1537),
 'kill': np.int64(1088),
 'way home': np.int64(2329),
 'good': np.int64(848),
 'girl': np.int64(816),
 'situat': np.int64(1892),
 'part': np.int64(1542),
 'check': np.int64(337),
 'iq': np.int64(1032),
 'took': np.int64(2164),
 'forev': np.int64(728),
 'come': np.int64(394),
 'ok come': np.int64(1477),
 'doubl': np.int64(559),
 'hair': np.int64(902),
 'said': np.int64(1792),
 'wun': np.int64(2443),
 'cut': np.int64(470),
 'short': np.int64(1867),
 'nice': np.int64(1415),
 'advis': np.int64(27),
 'follow': np.int64(722),
 'recent': np.int64(1723),
 'review': np.int64(1762),
 'mob': np.int64(1316),
 'award': np.int64(128),
 'bonu': np.int64(194),
 'award bonu': np.int64(129),
 'prize call': np.int64(1672),
 'song': np.int64(1923),
 'frnd': np.int64(775),
 'rpli': np.int64(1781),
 'send ur': np.int64(1842),
 'complimentari': np.int64(406),
 'trip': np.int64(2184),
 'di': np.int64(528),
 'ls': np.int64(1222),
 'ur award': np.int64(2235),
 'hear': np.int64(919),
 'lucki': np.int64(1230),
 'save': np.int64(1805),
 'money': np.int64(1337),
 'hee': np.int64(923),
 'hi': np.int64(932),
 'babe': np.int64(136),
 'im': np.int64(997),
 'wanna': np.int64(2309),
 'someth': np.int64(1918),
 'xx': np.int64(2461),
 'hi babe': np.int64(933),
 'call free': np.int64(248),
 'that': np.int64(2109),
 'cool': np.int64(430),
 'respect': np.int64(1753),
 'that cool': np.int64(2110),
 'peopl': np.int64(1557),
 'much': np.int64(1363),
 'pa': np.int64(1532),
 'oper': np.int64(1504),
 'job': np.int64(1055),
 'ta': np.int64(2057),
 'ah': np.int64(40),
 'hi hi': np.int64(935),
 'stop': np.int64(1992),
 'urgnt': np.int64(2261),
 'real': np.int64(1713),
 'yo': np.int64(2490),
 'ticket': np.int64(2130),
 'one': np.int64(1494),
 'start': np.int64(1975),
 'came': np.int64(278),
 'bed': np.int64(166),
 'gotta': np.int64(867),
 'came back': np.int64(279),
 'kano': np.int64(1070),
 'il': np.int64(995),
 'download': np.int64(561),
 'wen': np.int64(2358),
 'wen ur': np.int64(2359),
 'stand': np.int64(1971),
 'close': np.int64(370),
 'anoth': np.int64(72),
 'night': np.int64(1418),
 'spent': np.int64(1955),
 'late': np.int64(1124),
 'afternoon': np.int64(35),
 'mean': np.int64(1271),
 'includ': np.int64(1006),
 'smile': np.int64(1905),
 'pleasur': np.int64(1616),
 'troubl': np.int64(2185),
 'rain': np.int64(1695),
 'sum': np.int64(2027),
 'hurt': np.int64(985),
 'becoz': np.int64(165),
 'someon': np.int64(1916),
 'servic': np.int64(1849),
 'repres': np.int64(1750),
 'guarante': np.int64(885),
 'call custom': np.int64(247),
 'custom servic': np.int64(469),
 'servic repres': np.int64(1851),
 'repres pm': np.int64(1751),
 'pm guarante': np.int64(1624),
 'guarante cash': np.int64(887),
 'cash prize': np.int64(310),
 'havent': np.int64(917),
 'plan': np.int64(1604),
 'buy': np.int64(231),
 'show': np.int64(1868),
 'collect': np.int64(384),
 'simpli': np.int64(1881),
 'password': np.int64(1549),
 'verifi': np.int64(2275),
 'fml': np.int64(721),
 'free rington': np.int64(755),
 'movi': np.int64(1350),
 'abt': np.int64(4),
 'wat abt': np.int64(2322),
 'load': np.int64(1187),
 'loan': np.int64(1188),
 'wk': np.int64(2401),
 'hol': np.int64(946),
 'forgot': np.int64(730),
 'appoint': np.int64(88),
 'shower': np.int64(1871),
 'caus': np.int64(314),
 'prob': np.int64(1676),
 'need get': np.int64(1392),
 'get home': np.int64(805),
 'noth': np.int64(1445),
 'els': np.int64(596),
 'okay': np.int64(1489),
 'price': np.int64(1665),
 'long': np.int64(1198),
 'ave': np.int64(123),
 'gone': np.int64(845),
 'drive': np.int64(569),
 'test': np.int64(2094),
 'yet': np.int64(2487),
 'guess': np.int64(893),
 'gave': np.int64(793),
 'men': np.int64(1281),
 'chang': np.int64(326),
 'locat': np.int64(1190),
 'nyc': np.int64(1460),
 'cuz': np.int64(472),
 'page': np.int64(1535),
 'umma': np.int64(2217),
 'life': np.int64(1164),
 'lot': np.int64(1209),
 'dear': np.int64(506),
 'love lot': np.int64(1216),
 'wish': np.int64(2391),
 'birthday': np.int64(182),
 'truli': np.int64(2187),
 'aight': np.int64(44),
 'hit': np.int64(938),
 'would': np.int64(2430),
 'address': np.int64(20),
 'consid': np.int64(418),
 'comput': np.int64(407),
 'old': np.int64(1491),
 'better': np.int64(176),
 'lie': np.int64(1163),
 'busi': np.int64(230),
 'go dinner': np.int64(827),
 'thing': np.int64(2113),
 'scare': np.int64(1810),
 'mah': np.int64(1238),
 'contact': np.int64(419),
 'last': np.int64(1119),
 'draw': np.int64(562),
 'hr': np.int64(976),
 'ppm': np.int64(1653),
 'tri contact': np.int64(2181),
 'contact last': np.int64(423),
 'last weekend': np.int64(1123),
 'weekend draw': np.int64(2349),
 'draw show': np.int64(564),
 'show prize': np.int64(1869),
 'prize guarante': np.int64(1674),
 'guarante call': np.int64(886),
 'code valid': np.int64(379),
 'valid hr': np.int64(2272),
 'hr ppm': np.int64(977),
 'wa': np.int64(2297),
 'anyway': np.int64(82),
 'juz': np.int64(1068),
 'eatin': np.int64(587),
 'weight': np.int64(2353),
 'haha': np.int64(900),
 'happen': np.int64(909),
 'enter': np.int64(612),
 'cabin': np.int64(236),
 'boss': np.int64(199),
 'felt': np.int64(685),
 'askd': np.int64(107),
 'apart': np.int64(84),
 'went': np.int64(2360),
 'enter cabin': np.int64(613),
 'cabin pa': np.int64(237),
 'pa said': np.int64(1533),
 'said happi': np.int64(1793),
 'happi day': np.int64(912),
 'day boss': np.int64(495),
 'boss felt': np.int64(200),
 'felt special': np.int64(686),
 'special askd': np.int64(1947),
 'askd lunch': np.int64(108),
 'lunch lunch': np.int64(1234),
 'lunch invit': np.int64(1233),
 'invit apart': np.int64(1025),
 'apart went': np.int64(85),
 'holiday': np.int64(950),
 'flight': np.int64(717),
 'inc': np.int64(1004),
 'min': np.int64(1290),
 'winner special': np.int64(2390),
 'special select': np.int64(1950),
 'select receiv': np.int64(1831),
 'flight inc': np.int64(718),
 'speak live': np.int64(1944),
 'live oper': np.int64(1185),
 'oper claim': np.int64(1505),
 'must': np.int64(1370),
 'friday': np.int64(764),
 'hmm': np.int64(943),
 'uncl': np.int64(2221),
 'inform': np.int64(1013),
 'school': np.int64(1812),
 'directli': np.int64(540),
 'food': np.int64(724),
 'privat': np.int64(1669),
 'account': np.int64(9),
 'statement': np.int64(1978),
 'identifi': np.int64(992),
 'expir': np.int64(652),
 'privat account': np.int64(1670),
 'account statement': np.int64(10),
 'statement show': np.int64(1979),
 'point claim': np.int64(1635),
 'call identifi': np.int64(250),
 'identifi code': np.int64(993),
 'code expir': np.int64(377),
 'landlin': np.int64(1111),
 'box': np.int64(205),
 'urgent mobil': np.int64(2258),
 'mobil award': np.int64(1319),
 'bonu caller': np.int64(195),
 'caller prize': np.int64(272),
 'contact call': np.int64(420),
 'call landlin': np.int64(253),
 'voda': np.int64(2288),
 'number': np.int64(1453),
 'match': np.int64(1257),
 'quot': np.int64(1693),
 'standard': np.int64(1972),
 'app': np.int64(86),
 'today voda': np.int64(2151),
 'voda number': np.int64(2289),
 'number end': np.int64(1455),
 'end select': np.int64(602),
 'receiv award': np.int64(1721),
 'match pleas': np.int64(1258),
 'call quot': np.int64(260),
 'quot claim': np.int64(1694),
 'code standard': np.int64(378),
 'standard rate': np.int64(1973),
 'mu': np.int64(1362),
 'predict': np.int64(1658),
 'wat time': np.int64(2323),
 'time finish': np.int64(2135),
 'sent': np.int64(1844),
 'bother': np.int64(201),
 'del': np.int64(516),
 'bak': np.int64(145),
 'long time': np.int64(1199),
 'give call': np.int64(818),
 'dear call': np.int64(507),
 'answer': np.int64(74),
 'sunshin': np.int64(2034),
 'quiz': np.int64(1692),
 'top': np.int64(2165),
 'soni': np.int64(1924),
 'dvd': np.int64(579),
 'player': np.int64(1608),
 'countri': np.int64(441),
 'sp': np.int64(1940),
 'sunshin quiz': np.int64(2035),
 'wkli win': np.int64(2408),
 'win top': np.int64(2384),
 'soni dvd': np.int64(1925),
 'player know': np.int64(1609),
 'know countri': np.int64(1097),
 'sp tyron': np.int64(1941),
 'laid': np.int64(1107),
 'dog': np.int64(550),
 'direct': np.int64(539),
 'join': np.int64(1058),
 'largest': np.int64(1117),
 'bt': np.int64(219),
 'txting': np.int64(2210),
 'nt': np.int64(1447),
 'ec': np.int64(588),
 'want get': np.int64(2312),
 'sent direct': np.int64(1845),
 'ur mob': np.int64(2246),
 'join uk': np.int64(1059),
 'largest dog': np.int64(1118),
 'haf': np.int64(899),
 'yiju': np.int64(2488),
 'befor': np.int64(170),
 'activ': np.int64(16),
 'chat': np.int64(333),
 'age': np.int64(38),
 'yr': np.int64(2493),
 'go get': np.int64(828),
 'lazi': np.int64(1138),
 'type': np.int64(2213),
 'lect': np.int64(1148),
 'sir': np.int64(1887),
 'mail': np.int64(1240),
 'sir wait': np.int64(1888),
 'swt': np.int64(2055),
 'tire': np.int64(2139),
 'littl': np.int64(1182),
 'lovabl': np.int64(1210),
 'person': np.int64(1569),
 'coz': np.int64(445),
 'heart': np.int64(921),
 'gud': np.int64(888),
 'ni': np.int64(1414),
 'gud ni': np.int64(891),
 'open': np.int64(1503),
 'ya': np.int64(2464),
 'ye see': np.int64(2475),
 'what': np.int64(2363),
 'sexi': np.int64(1856),
 'local': np.int64(1189),
 'luv': np.int64(1235),
 'netcollex': np.int64(1397),
 'ltd': np.int64(1227),
 'per msg': np.int64(1563),
 'repli stop': np.int64(1747),
 'stop end': np.int64(1994),
 'begin': np.int64(171),
 'qatar': np.int64(1687),
 'pray': np.int64(1657),
 'hard': np.int64(914),
 'delet': np.int64(518),
 'got job': np.int64(863),
 'wine': np.int64(2388),
 'thk': np.int64(2119),
 'yup thk': np.int64(2498),
 'need go': np.int64(1393),
 'window': np.int64(2387),
 'shirt': np.int64(1863),
 'sometim': np.int64(1921),
 'dream': np.int64(566),
 'without': np.int64(2399),
 'joy': np.int64(1063),
 'tv': np.int64(2197),
 'becom': np.int64(164),
 'leav': np.int64(1146),
 'hous': np.int64(970),
 'leav hous': np.int64(1147),
 'interview': np.int64(1022),
 'boy': np.int64(208),
 'arrang': np.int64(100),
 'new year': np.int64(1410),
 'receiv cash': np.int64(1722),
 'cash holiday': np.int64(309),
 'keep': np.int64(1073),
 'safe': np.int64(1791),
 'everyon': np.int64(637),
 'miss alreadi': np.int64(1307),
 'parent': np.int64(1539),
 'hand': np.int64(906),
 'new job': np.int64(1404),
 'excit': np.int64(646),
 'spend': np.int64(1954),
 'invit friend': np.int64(1026),
 'friend repli': np.int64(769),
 'see www': np.int64(1827),
 'www sm': np.int64(2449),
 'stop send': np.int64(1998),

In [76]:
y = pd.get_dummies(messages['label'])

In [77]:
y

        ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [78]:
y = y['ham'].astype(int).values

In [79]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [81]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)

In [82]:
from sklearn.metrics import confusion_matrix
confusion_m=confusion_matrix(y_test,y_pred)

In [83]:
confusion_m

array([[134,  16],
       [  6, 959]])

In [84]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [85]:
accuracy

0.9802690582959641